spring:
  profiles:
    active: git
  devtools:
    restart:
      poll-interval: 2s
  config:
    import: "configserver:"
  application:
    name: mail-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

logging:
  level:
    org:
      springframework:
        security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"